### ISSUE TITLE
Failed to retrieve ERC20 token decimals/scale value

### ISSUE THREAD

**Issue by karthikshaml** [furqansiddiqui/erc20-php#12]
Hi @furqansiddiqui,

Thanks for your ERC20 Library. am using your library and getting the below error.

ERC20\Exception\ERC20Exception: Failed to retrieve ERC20 token decimals/scale value in file /var/www/html/tokendash/vendor/furqansiddiqui/erc20-php/src/ERC20_Token.php on line 101

Looking forward your suggestions/help to fix the issues.

Thanks

**Comment by survivordj** [comment]
I have created a pull request for this.

**Comment by furqansiddiqui** [comment]
> 
> 
> I have created a pull request for this.

Thank you, pull request merged
