### ISSUE TITLE
Problem Infura personal_sendTransaction

### ISSUE THREAD

**Issue by Lunkero** [furqansiddiqui/erc20-php#13]
I have a problem, when i send a trx. 
Infura node dont support for "personal_sendTransaction", Infura do support for "eth_sendRawTransaction".

Any solution?

**Comment by furqansiddiqui** [comment]
I am sorry I will not be able to help you regarding Infura client, this lib is designed for Ethereum-Go (geth), If you find answer and is feasible, feel free to make pull request
