### ISSUE TITLE
Insufficient funds. 

### ISSUE THREAD

**Issue by Troodi** [furqansiddiqui/erc20-php#16]
The account you tried to send transaction from does not have enough funds.
Why? I have so much tokens and Ethereum.

**Comment by furqansiddiqui** [comment]
what is the amount/value argument you are sending perhaps you are sending in WEI or other units

**Comment by Troodi** [comment]
I have 1 000 000 000.00 tokens, and i trying send 1 000 tokens. 
`$amount = 1000;`
The greater the amount I have in Ethereum, the more I lack the information for translation.
I sending integer value, not wei.

**Comment by furqansiddiqui** [comment]
I don't think any exception as "Insufficient funds" is thrown from lib itself, I think it is merely carrying forward the message it has received from geth node you are connected to, perhaps try checking if your node is fully synced

**Comment by Troodi** [comment]
Yes, I also thought about it, thanks, I will try and write the result here.
