### ISSUE TITLE
Wallet generate child addresses

### ISSUE THREAD

**Issue by tonimonteiro** [furqansiddiqui/erc20-php#19]
We can generate a Wallet and from that Wallet generate child addresses. When these child addresses receive values, will the total be counted from the Primary Wallet?

The idea would be to keep the total amount received out of public reach.

Each time I receive a value, I generate an address for that transaction only and receive the value in the main Wallet.

Tks!

**Comment by furqansiddiqui** [comment]
All known issues have been resolved in latest release. Please checkout latest commit from master or 0.2.1 release.
