### ISSUE TITLE
How to send ERC20 Custom Token to ether address 

### ISSUE THREAD

**Issue by hsfzmsn** [furqansiddiqui/erc20-php#2]
Hi,

Is it possible to send ERC20 Custom Token to and ethereum address?
     $geth = new EthereumRPC($this->host, $this->port);
     $erc20 = new \ERC20\ERC20($geth);
      $token = $erc20->token('0x4c7e9.......');

      var_dump($token->transfer('0x30e3c....','1000000'));

but not yet received
think you!

**Comment by furqansiddiqui** [comment]
`transfer()` method is there to compliment standard ERC20 ABI, to transfer ERC20 tokens use `encodedTransferData()` method and use the returning string as value for `data` parameter of Ethereum transactions

**Comment by hsfzmsn** [comment]
Yes, much clearer. Thank you so much for your explanation.

**Comment by amandiobm** [comment]
@furqansiddiqui man, a very good job with this library, easy to use and config.

About send a token, and I read this.

> `transfer()` method is there to compliment standard ERC20 ABI, to transfer ERC20 tokens use `encodedTransferData()` method and use the returning string as value for `data` parameter of Ethereum transactions

Can you give me a code example of how to achieve that using your lib?

Kind Regards.

**Comment by amandiobm** [comment]
[Found it](https://github.com/furqansiddiqui/erc20-php/issues/1#issuecomment-398718242)

**Comment by furqansiddiqui** [comment]
[https://www.furqansiddiqui.com/transfer-erc20-token-from-one-account-to-another-using-php/](https://www.furqansiddiqui.com/transfer-erc20-token-from-one-account-to-another-using-php/)

**Comment by Amsori** [comment]
> https://www.furqansiddiqui.com/transfer-erc20-token-from-one-account-to-another-using-php/

the link is broker, can you give me alternate link... thanks before.
