### ISSUE TITLE
How do I pay gas use a third-party address when I transfer erc20 coin？

### ISSUE THREAD

**Issue by heropoo** [furqansiddiqui/erc20-php#20]
How do I pay gas use a third-party address when I transfer erc20 coin？

**Comment by burnside** [comment]
You issue the contract transfer request from the third party address.

**Comment by furqansiddiqui** [comment]
You could use "transferFrom" method if your ERC20 contract supports that but for that you might have to set allowance for the spender and to perform that action you will need gas as well, so its safe to assume you will need to fund some ETH to account that holds tokens for gas.
