### ISSUE TITLE
Expected "application/json", got "text/html" when using hostname

### ISSUE THREAD

**Issue by akegaviar** [furqansiddiqui/erc20-php#22]
Thanks a lot for this package.

I'm wondering if you could please update it to work with node providers like [Chainstack](https://chainstack.com/build-better-with-ethereum/).

Chainstack nodes use Geth and support RPC. The only issue is that (as I understand) is this package expects an IP address and Chainstack uses a hostname with basic auth. A Geth node with RPC from Chainstack has a hostname like `https://user-name:pass-word@nd-123-456-789.p2pify.com`.

So using it is resulting in an error similar to this:

```
Fatal error: Uncaught EthereumRPC\Exception\ConnectionException: Expected "application/json", got "text/html" 
```

By looking [here](https://github.com/furqansiddiqui/erc20-php/issues/3#issuecomment-396755432) and [here](https://github.com/furqansiddiqui/erc20-php/issues/3#issuecomment-396760241) I think the package expects an IP address.

Thanks!

**Comment by furqansiddiqui** [comment]
All known issues have been resolved in latest release. Please checkout latest commit from master or 0.2.1 release.
