### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by frmiqueias** [furqansiddiqui/erc20-php#25]
Problem 1
    - Installation request for furqansiddiqui/ethereum-php ^0.1.1 -> satisfiable by furqansiddiqui/ethereum-php[0.1.1].
    - furqansiddiqui/ethereum-php 0.1.1 requires furqansiddiqui/bip32-keypair-php dev-master#57ec344 -> satisfiable by furqansiddiqui/bip32-keypair-php[dev-master] but these conflict with your requirements or minimum-stability.

**Comment by lessmore92** [comment]
How did you solve this issue?

**Comment by furqansiddiqui** [comment]
Do you have minimum stability set to dev?

`  "minimum-stability": "dev",`

**Comment by lessmore92** [comment]
Thanks.
`"minimum-stability": "dev",` solve the problem.

**Comment by herohelpme** [comment]
> Thanks.
> `"minimum-stability": "dev",` solve the problem.

chang to "dev", not work. Same problem at 1st.

**Comment by furqansiddiqui** [comment]
> 
> 
> > Thanks.
> > `"minimum-stability": "dev",` solve the problem.
> 
> chang to "dev", not work. Same problem at 1st.

please paste the exact error messages you're getting while installing via composer

**Comment by herohelpme** [comment]
Problem 1
    - furqansiddiqui/ethereum-php 0.1.20 requires furqansiddiqui/bip32-keypair-php dev-master#57ec344 -> found furqansiddiqui/bip32-keypair-php[dev-master] but it does not match your minimum-stability.
    - furqansiddiqui/erc20-php 0.2.2 requires furqansiddiqui/ethereum-php ^0.1.20 -> satisfiable by furqansiddiqui/ethereum-php[0.1.20].
    - Root composer.json requires furqansiddiqui/erc20-php ^0.2.2 -> satisfiable by furqansiddiqui/erc20-php[0.2.2].


> > > Thanks.
> > > `"minimum-stability": "dev",` solve the problem.
> > 
> > 
> > chang to "dev", not work. Same problem at 1st.
> 
> please paste the exact error messages you're getting while installing via composer
