### ISSUE TITLE
how does call contract method 

### ISSUE THREAD

**Issue by PHPJourney** [furqansiddiqui/erc20-php#27]
In project code,i can't see use `call` call other method.

now i can use token get token info and balance

like `approve` something

**Comment by PHPJourney** [comment]
approveAndCall params bytes type can't use `encodeArg`

**Comment by xcc369** [comment]
did you fix that problem?

**Comment by atlaschiew** [comment]
@PHPJourney @xcc369 

`In project code,i can't see use call call other method.`
not sure is this https://www.btcschools.net/ethereum/eth_call.php helpful to u? shortly, say you use infura's node, then next you need to get encoded param and trigger `eth_call` method .

`approveAndCall params bytes type can't use encodeArg`
i have added encode bytes type in https://www.btcschools.net/ethereum/eth_abi_data_encoding.php. @furqansiddiqui i modify this on top of your codings actually, so you may enhance it in your repo. thanks

Atlas Chiew
btcschools.net
