### ISSUE TITLE
Cannot get an Output

### ISSUE THREAD

**Issue by vanshtah** [furqansiddiqui/erc20-php#30]
```
    $geth = new EthereumRPC('x.x.x.x', 8545);
    $erc20 = new \ERC20\ERC20($geth);

    $usdt = $erc20->token("0xdac17f958d2ee523a2206206994597c13d831ec7");
    dd($usdt->name());
```

I used the above code but the output is empty

**Comment by arnezt** [comment]
The code is just work well if you have fully synchronized.

**Comment by vanshtah** [comment]
It is fully synchronised

**Comment by arnezt** [comment]
> It is fully synchronised

Try this manually on console, if it gets output:

`geth attach http://localhost:8545`
`personal.listAccounts`

or with cUrl:

`curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1}' http://your-ip-address:8545`

**Comment by vanshtah** [comment]
I got the response with all accounts created in the node

**Comment by arnezt** [comment]
I used this more than one year ago and worked, I don't know if its still work now, before I use `sc0vu/web3.php` script:

`<?php`
`declare(strict_types=1);`
`require __DIR__ . '/vendor/autoload.php';`

`use EthereumRPC\EthereumRPC;`
`use ERC20\ERC20;`
 
// Instantiate Ethereum RPC lib with your server credentials (i.e. Ethereum-Go)
// This example assumes Ethereum RPC server running on standard port 8545 on localhost
`$geth = new EthereumRPC('your-ip', 8545);`
 
// Instantiate ERC20 lib by passing Instance of EthereumRPC lib as constructor argument
`$erc20 = new ERC20($geth);`
`$token = $erc20->token("token-contract");`
// $token is now an instance of "ERC20_Token" class, now let's retrieve basic details about this token
 
`var_dump($token->name()) . PHP_EOL;` // string(7) "Zilliqa"
`var_dump($token->decimals()) . PHP_EOL;` // int(12)
`var_dump($token->symbol()) . PHP_EOL;` // string(3) "ZIL"
`var_dump($token->totalSupply()) . PHP_EOL;` // string(24) "12600000000.000000000000"

`var_dump($token->balanceOf("your-eth-address"));` //get balance of an address
