### ISSUE TITLE
Class 'FurqanSiddiqui\Ethereum\Ethereum' not found 

### ISSUE THREAD

**Issue by brokenpieworld** [furqansiddiqui/erc20-php#33]
Class 'FurqanSiddiqui\Ethereum\Ethereum' not found

**Comment by Farhadesfandiar** [comment]
Undefined type 'EthereumRPC\EthereumRPC' error comes up after installing both "furqansiddiqui/ethereum-php": "^0.1.20" and "furqansiddiqui/erc20-php": "dev-master". The same error for ERC20! I also tried "furqansiddiqui/ethereum-php": "dev-master" but the same error!
