### ISSUE TITLE
Transfer tokens not working

### ISSUE THREAD

**Issue by gatepavel** [furqansiddiqui/erc20-php#34]
old code from https://www.furqansiddiqui.com/transfer-erc20-token-from-one-account-to-another-using-php/ not worked - method personal() not found

**Comment by matrix543** [comment]
$transaction = $geth->personal()->transaction($payer, $contract) // from $payer to $contract address
  ->amount("0") // Amount should be ZERO
  ->data($data); // Our encoded ERC20 token transfer data from previous step

**Comment by Farhadesfandiar** [comment]
The same error here, with "dev-master" version!

**Comment by Farhadesfandiar** [comment]
personal, in "$transaction = $geth->personal()->transaction($payer, $contract)" is exist in EthereumRPC. You may chek [this issue](https://github.com/furqansiddiqui/erc20-php/issues/1) (which wasn't actually an issue). So you need to also install EthereumRPC via 
`composer require furqansiddiqui/ethereum-rpc`
[](https://github.com/furqansiddiqui/ethereum-rpc)

**Comment by isszz** [comment]
It should be replaced by ethereum-php, the previous method is no longer available.
May I ask how the transfer using ethereum-php is done now?

**Comment by isszz** [comment]
Maybe so?
`
$eth = new \FurqanSiddiqui\Ethereum\Ethereum();
$erc20 = new \FurqanSiddiqui\Ethereum\ERC20\ERC20($eth);
$usdt = $erc20->token($contractAddress);

$payer = '0x...';
$payee = '0x...';
$amount = '0';
$data = $bnb->encodedTransferData($eth->getAccount($payee), $amount);

$tx = \FurqanSiddiqui\Ethereum\Transactions\TxBuilder($eth);

$transaction = $tx->gas(\FurqanSiddiqui\Ethereum\Math\WEIValue('1'), 70000)
	->to($eth->getAccount($payer))
	->value(\FurqanSiddiqui\Ethereum\Math\WEIValue('0'))
	->data($data);
`
