### ISSUE TITLE
Composer dont work on php 8

### ISSUE THREAD

**Issue by matrix543** [furqansiddiqui/erc20-php#35]
Composer fail if you run php 8.05

**Comment by matrix543** [comment]
Problem 1
    - furqansiddiqui/erc20-php[0.1.4, ..., 0.1.x-dev] require furqansiddiqui/ethereum-rpc ^0.1.5 -> satisfiable by furqansiddiqui/ethereum-rpc[0.1.5].
    - furqansiddiqui/ethereum-rpc 0.1.5 requires php ^7.1.0 -> your php version (8.0.5) does not satisfy that requirement.
    - Root composer.json requires furqansiddiqui/erc20-php ^0.1.4 -> satisfiable by furqansiddiqui/erc20-php[0.1.4, 0.1.x-dev].

**Comment by hbedek** [comment]
Same here for me ...

**Comment by aliqasemzadeh** [comment]
I have this problem too.
You can install it with --ignore-platform-reqs

**Comment by matrix543** [comment]
I did a solution where I fork the repo edited it to work with php8  uploaded it so I could install the package with composer from my own repo

**Comment by matrix543** [comment]
composer require matrix543/erc20-php

**Comment by matrix543** [comment]
in your laravel controller 

use EthereumRPC\EthereumRPC;
use ERC20\ERC20;

	public static function getbalance($address){
		$id = Auth::id();
		
		$geth = new EthereumRPC('127.0.0.1', '8545');
		$token_contract = <ETH token contract addr>
		
		$erc20 = new ERC20($geth);
		
		$token = $erc20->token($token_contract);
		$balance = $token->balanceOf($address);
		
		return $balance;
		
	}

**Comment by matrix543** [comment]
in composer json

**Comment by matrix543** [comment]
"matrix543/erc20-php": "^0.1.4",
 "matrix543/ethereum-rpc": "^0.1.5",

**Comment by matrix543** [comment]
it talks to a geth node that you run on your lokal pc or a vps you can connect metamask to a lokal geth node to

**Comment by aliqasemzadeh** [comment]
I want to use metamask RPCs to get balance of address in php without running full node.

**Comment by matrix543** [comment]
it depends if metamask let you connect to an ip and port the php package will work otherwise you have to run geth with lightmode on a server so it dosent eat up your hard drive

geth --syncmode "light"
