### ISSUE TITLE
Composer can not be installed.

### ISSUE THREAD

**Issue by anyluck** [furqansiddiqui/erc20-php#5]
Using version ^0.1.1 for furqansiddiqui/erc20-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for furqansiddiqui/erc20-php ^0.1.1 -> satisfiable by furqansiddiqui/erc20-php[0.1.1].
    - furqansiddiqui/erc20-php 0.1.1 requires furqansiddiqui/ethereum-rpc dev-master -> satisfiable by furqansiddiqui/ethereum-rpc[dev-master] but these conflict with your requirements or minimum-stabili
ty.

Installation failed, reverting ./composer.json to its original content.

**Comment by furqansiddiqui** [comment]
There are two solutions to this problem:

1. quick and local fix: adding `"minimum-stability": "dev"` in your composer.json file will resolve that.

2. However for more permanent fix, I have changed composer.json dependency from dev-master to >=0.1.1 for ethereum-rpc package 

**Try to install 0.1.2 package of erc20-php now.**

let me know if still any problem

**Comment by azhahesan-maze** [comment]
where I find that 0.1.2 package of erc20-php
